security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
    providers:
        db_provider:
            id: app.user_provider

    firewalls:
          login:
              pattern:  ^/api/login
              stateless: true
              anonymous: true
              form_login:
                  check_path:               api_login
                  success_handler:          lexik_jwt_authentication.handler.authentication_success
                  failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                  require_previous_session: false
                  username_parameter:             email
                  password_parameter:             password

          api:
              pattern:   ^/api/
              stateless: true
              guard:
                  authenticators:
                      - lexik_jwt_authentication.jwt_token_authenticator

    access_control:

        - { path: ^/api/profile,   roles: [ROLE_USER] }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
