# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  app.user_provider:
    class: AppBundle\Services\UserProvider
    arguments: ["@doctrine.orm.entity_manager"]

  app.event.authentication_success_listener:
      class: AppBundle\EventListener\AuthenticationSuccessListener
      arguments: ['@serializer']
      tags:
          - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }

  app.letter_manager:
      class: AppBundle\Services\LetterManager
      arguments: ["@doctrine.orm.entity_manager", '@app.github_api', '@app.mailer', '@app.weather_service']

  app.github_api:
      class: AppBundle\Services\GithubApi

  app.mailer:
      class: AppBundle\Services\Mailer\AppEmailsGenerator
      arguments: ['@swiftmailer.mailer', '@twig']

  app.weather_service:
      class: AppBundle\Services\Weather\WeatherService
      arguments: ['%owm.api_key%', '@app.weather_formatter_html']

  app.weather_formatter_html:
      class: AppBundle\Services\Weather\OWMWeatherToHTML
