<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * ContractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractRepository extends EntityRepository
{
    public function findContractsByUser(User $user)
    {
        $qb = $this->createQueryBuilder('l');

        $qb
            ->select('l')
            ->join('l.user', 'u')
            ->where('u.id = :userId')
            ->setParameters(['userId' => $user->getId()]);

        return $qb;
    }
}
